import os

from dotenv import load_dotenv


load_dotenv()

DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_PORT = os.getenv("DATABASE_PORT")

TEST_DATABASE_USER = os.getenv("TEST_DATABASE_USER")
TEST_DATABASE_PASSWORD = os.getenv("TEST_DATABASE_PASSWORD")
TEST_DATABASE_NAME = os.getenv("TEST_DATABASE_NAME")
TEST_DATABASE_HOST = os.getenv("TEST_DATABASE_HOST")
TEST_DATABASE_PORT = os.getenv("TEST_DATABASE_PORT")
